### ISSUE TITLE
Protocols and No Devices Found

### ISSUE THREAD

**Issue by esmoyer** [va7eex/docker-rtl433#2]
Was super happy to find this as I have been wanting to move my RTL to docker.

I too am getting the same message "No Supported Devices Found" as https://github.com/va7eex/docker-rtl433/issues/1

I also noticed that the protocols end at 153 but merbanan's goes up to 245. Is that just a limitation of this repo?

Thanks for the work!

**Comment by va7eex** [comment]
Hello, this repository hasn't been updated in three years. I'll push an update soon but in the meantime you can execute `git submodule update --remote --merge` before building the container.

**Comment by esmoyer** [comment]
Oh dang, sorry about that, I just saw April 18th on the other issue and completely ignored the year! Disregard, I will keep searching. Thanks!

**Comment by va7eex** [comment]
https://github.com/va7eex/docker-rtl433/commit/aca9b8c43d8a298eeba13036ff0a2f09c9f84408 the repository has been updated.

You can now pull `ghcr.io/va7eex/rtl433:base`/`ghcr.io/va7eex/rtl433:mqtt` with up to date code.

**Comment by esmoyer** [comment]
Awesome, thank you much!
